# Generated by Django 4.1.4 on 2022-12-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(editable=False, max_length=100)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(default="", max_length=50, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=15)),
                ("confirm_password", models.CharField(max_length=15)),
            ],
        ),
    ]
